### ISSUE TITLE
Consider using GitHub releases

### ISSUE THREAD

**Issue by lmartinez-mirror** [actuday6418/Diary#1]
It would be great to see this project use GitHub releases to track milestones in the project, or at the very least git tags, something that stays in sync with cargo's version.

**Comment by actuday6418** [comment]
Hello! Thanks for your feedback. 

I figured earlier that it would be best for users to install the binary via ```cargo install``` (it compiles from source).
One major issue I see with GitHub releases is the lack of a bother free update method. But I understand that it would be convenient to have binary releases as well for some users. I'll get that done tomorrow.

**Comment by actuday6418** [comment]
First release published.
